version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8089:8080"
    volumes:
      - ./keycloak-import:/opt/keycloak/data/import
    restart: unless-stopped 

  frontend:
    build:
      context: ./frontend
    container_name: myfirstgitapp-frontend
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    depends_on:
      - keycloak

  nginx:
    image: nginx:alpine
    container_name: myfirstgitapp-nginx
    ports:
      - "3000:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend 