apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - start-dev
            - --import-realm
          env:
            - name: KC_HOSTNAME
              value: myfirstgitapp.local
            - name: KC_HTTP_RELATIVE_PATH
              value: /libertyX/auth
            - name: KC_PROXY
              value: edge
            - name: KC_HTTP_PORT
              value: "8080"
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          image: quay.io/keycloak/keycloak:24.0.4
          name: keycloak
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: keycloak-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: keycloak-cm0
          name: keycloak-cm0
