apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: myfirstgitapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.4
          args: ["start-dev", "--import-realm"]
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_HOSTNAME
              value: dev2.sophia.com
            - name: KC_HTTP_PORT
              value: "8080"
            - name: KC_HOSTNAME_PORT
              value: "8089"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm-import
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: realm-import
          configMap:
            name: keycloak-realm
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: myfirstgitapp
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32089
  selector:
    app: keycloak
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: myfirstgitapp
data:
  myapp-realm.json: |
    // ... Paste content of keycloak-import/myapp-realm.json here
