apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: myfirstgitapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.4
          args: ["start-dev", "--import-realm"]
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/libertyX/auth"
            - name: KC_HOSTNAME_URL
              value: "https://olite.hd.free.fr/libertyX/auth"
            - name: KC_HOSTNAME_ADMIN_URL
              value: "https://olite.hd.free.fr/libertyX/auth"
            - name: KC_PROXY
              value: "edge"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm-import
              mountPath: /opt/keycloak/data/import
            - name: custom-theme-properties
              mountPath: /opt/keycloak/themes/custom/login/theme.properties
              subPath: theme.properties
            - name: custom-theme-css
              mountPath: /opt/keycloak/themes/custom/login/resources/css/login.css
              subPath: login.css
      volumes:
        - name: realm-import
          configMap:
            name: keycloak-realm
        - name: custom-theme-properties
          configMap:
            name: keycloak-custom-theme
            items:
              - key: theme.properties
                path: theme.properties
        - name: custom-theme-css
          configMap:
            name: keycloak-custom-theme
            items:
              - key: login.css
                path: login.css
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: myfirstgitapp
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32089
  selector:
    app: keycloak
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: myfirstgitapp
data:
  myapp-realm.json: |
    {
      "realm": "myapp",
      "enabled": true,
      "clients": [
        {
          "clientId": "myapp-client",
          "enabled": true,
          "publicClient": true,
          "redirectUris": [
            "http://dev2.sophia.com/libertyX/api/auth/callback/keycloak",
            "http://dev2.sophia.com/libertyX/callback/keycloak",
            "http://dev2.sophia.com/libertyX/*",
            "https://myfirstgitapp.local/libertyX/*",
            "https://myfirstgitapp.local/libertyX/api/auth/callback/keycloak",
            "https://myfirstgitapp.local/libertyX/callback/keycloak",
            "https://olite.hd.free.fr/libertyX/*",
            "https://olite.hd.free.fr/libertyX/api/auth/callback/keycloak",
            "https://olite.hd.free.fr/libertyX/callback/keycloak"
          ],
          "webOrigins": [
            "http://dev2.sophia.com",
            "http://localhost:3000",
            "https://myfirstgitapp.local",
            "https://olite.hd.free.fr"
          ]
        }
      ],
      "users": [
        {
          "username": "mcharpen",
          "enabled": true,
          "email": "marc.charpentier@icloud.com",
          "firstName": "Marc",
          "lastName": "Charpentier",
          "credentials": [
            {
              "type": "password",
              "value": "mypassword",
              "temporary": false
            }
          ]
        }
      ]
    }

