[master]
dev2 ansible_host=10.17.1.145 ansible_user=mcharpen

[workers]
#worker1 ansible_host=10.17.1.146 ansible_user=mcharpen
#worker2 ansible_host=10.17.1.147 ansible_user=mcharpen
#worker3 ansible_host=10.17.1.148 ansible_user=mcharpen

