apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  creationTimestamp: "2025-12-03T17:23:11Z"
  name: default-ipv4-ippool
  resourceVersion: "132050"
  uid: 0f038c58-db8b-4554-b08b-77eea4170227
spec:
  allowedUses:
  - Workload
  - Tunnel
  blockSize: 26
  cidr: 10.244.0.0/16
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: CrossSubnet
